mode: rule
log-level: info
subscribe-url: &suburl http://example.com

proxy-providers:
  Australia:
    url: *suburl
    interval: 86400
    filter: (?i)(🇦🇺|Australia|AU|澳)
  Brazil:
    url: *suburl
    interval: 86400
    filter: (?i)(🇧🇷|Brazil|BR|巴)
  Canada:
    url: *suburl
    interval: 86400
    filter: (?i)(🇨🇦|Canada|CA|加)
  Colombia:
    url: *suburl
    interval: 86400
    filter: (?i)(🇨🇴|Colombia|CO|哥)
  Germany:
    url: *suburl
    interval: 86400
    filter: (?i)(🇩🇪|Germany|DE|德)
  France:
    url: *suburl
    interval: 86400
    filter: (?i)(🇫🇷|France|FR|法)
  Hong Kong:
    url: *suburl
    interval: 86400
    filter: (?i)(🇭🇰|Hong Kong|HK|港)
  Iceland:
    url: *suburl
    interval: 86400
    filter: (?i)(🇮🇸|Iceland|IS|冰)
  India:
    url: *suburl
    interval: 86400
    filter: (?i)(🇮🇳|India|IN|印)
  Indonesia:
    url: *suburl
    interval: 86400
    filter: (?i)(🇮🇩|Indonesia|ID|尼)
  Japan:
    url: *suburl
    interval: 86400
    filter: (?i)(🇯🇵|Japan|JP|日)
  Korea:
    url: *suburl
    interval: 86400
    filter: (?i)(🇰🇷|Korea|KR|韩)
  Malaysia:
    url: *suburl
    interval: 86400
    filter: (?i)(🇲🇾|Malaysia|MY|来)
  Singapore:
    url: *suburl
    interval: 86400
    filter: (?i)(🇸🇬|Singapore|SG|坡)
  Taiwan:
    url: *suburl
    interval: 86400
    filter: (?i)(🇹🇼|Taiwan|TW|台)
  Thailand:
    url: *suburl
    interval: 86400
    filter: (?i)(🇹🇭|Thailand|TH|泰)
  United Arab Emirates:
    url: *suburl
    interval: 86400
    filter: (?i)(🇦🇪|United Arab Emirates|AE|伯)
  United Kingdom:
    url: *suburl
    interval: 86400
    filter: (?i)(🇬🇧|United Kingdom|GB|英)
  United States:
    url: *suburl
    interval: 86400
    filter: (?i)(🇺🇸|United States|US|美)
  Viet Nam:
    url: *suburl
    interval: 86400
    filter: (?i)(🇻🇳|Viet Nam|VN|越)
proxy-groups:
- name: $tash
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/bypass.png
  type: select
  proxies:
  - Auto
  - Available
  - Load Balance
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
- name: Auto
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/auto.png
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
- name: Available
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/available.png
  type: fallback
  url: http://www.gstatic.com/generate_204
  interval: 300
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
- name: Load Balance
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/roundrobin.png
  type: load-balance
  strategy: consistent-hashing
  url: http://www.gstatic.com/generate_204
  interval: 300
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
rules:
- GEOIP,CN,DIRECT
- MATCH,$tash
